name: main
on:
  # Should only be on push to main.
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create build folder
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: dist
          clean: true
          force: true
