name: main
on:
  # Should only be on push to main.
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create build folder
        run: npm run build

      - name: Store build folder as artifact for deploy
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  jest:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run jest
        run: npm run test:cov

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./coverage/lcov.info
          minimum-coverage: 50
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Downloads build as artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: build

      - name: Cypress E2E on chrome
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm run start
          wait-on: 'http://localhost:3000'

  gh-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Downloads build as artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
          path: build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: build
          clean: true
          force: true
